apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo-system
  description: "Demo system for workshop"
spec:
  owner: team-a
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: items-service
  description: "Go Echo service for Items API"
spec:
  type: service
  owner: team-a
  system: demo-system
  lifecycle: production
  providesApis: [items-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: items-api
  description: "The Items service API"
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  system: demo-system
  definition:
    $text: https://raw.githubusercontent.com/up1/workshop-develop-services-2025/main/openapi/openapi.yaml